[package]
name    = "vim-profiler"
version = "0.0.1"
authors = ["Liam <liam@scalzulli.com>"]
edition = "2018"

[[bin]]
name = "vp"
path = "src/main.rs"

[dependencies]
env_logger = "0.8.4"
log        = "0.4.14"
regex      = "1.0.0"
snafu      = "0.6.10"
structopt  = "0.3.22"
charts     = "0.3.0"

[dev-dependencies]
float-cmp = "0.8.0"
textwrap  = "0.14.2"
